### ISSUE TITLE
API requests always fail - missing "v" parameter

### ISSUE THREAD

**Issue by swese44** [simonengelhardt/meteor-foursquare#1]
This package no longer works, Foursquare now requires a "v" parameter (date string in format yyyymmdd) in all API requests:
https://developer.foursquare.com/overview/versioning

Line 65 of foursquare_server.js needs an additional param, something like "v: '20140325'". To keep the API up to date, generate the string from the current date. This should be adequate for most applications and would be the quickest fix, but you may want to add an option to set a specific date as well.

```
> Exception while invoking method 'login' Error: Failed to fetch identity from Foursquare. failed [410] {"meta":{"code":410,"errorType":"param_error","errorDetail":"The Foursquare API no longer supports requests that do not pass in a version parameter. For more de...
>     at getIdentity (packages/foursquare/foursquare_server.js:68)
>     at Object.userAgent [as handleOauthRequest] (packages/foursquare/foursquare_server.js:6)
>     at Oauth._requestHandlers.(anonymous function) (packages/oauth2/oauth2_server.js:9)
>     at middleware (packages/oauth/oauth_server.js:106)
>     at packages/oauth/oauth_server.js:79
```

**Comment by simonengelhardt** [comment]
@swese44 thanks for the heads up. I'll push a fixing commit shortly and publish an updated version on Atmosphere. I've used the actual date when the API integration was verified (today, for this version) instead of just the current date, as that seemed to be the appropriate way to do it, following the Foursquare API docs.
