### ISSUE TITLE
Package still maintained? + comparison with @msamoylov's package

### ISSUE THREAD

**Issue by dandv** [simonengelhardt/meteor-foursquare#2]
Hi Simon,

I found https://atmospherejs.com/simon/foursquare on Atmosphere and noticed it hasn't been updated for the new packaging system released with Meteor 0.9.

@msamoylov seems to have released a [newer package](https://github.com/msamoylov/foursquare/). Maybe join forces? It's also possible to hide the old package from Atmosphere searches, but still keep it installable by dependent packages and apps:

```
meteor admin set-unmigrated simon:foursquare
```

Thanks,
Dan
Atmosphere curator

**Comment by simonengelhardt** [comment]
Hi Dan,

You are right. It's time for some spring cleaning.

My package was essentially only created to complement https://github.com/pius/meteor-accounts-foursquare (published as https://atmospherejs.com/mrt/accounts-foursquare), but that seems to have gone [a bit stale](https://github.com/pius/meteor-accounts-foursquare/pull/2).

@msamoylov's approach of maintaining both packages necessary to implement Foursquare login ([foursquare](https://atmospherejs.com/msamoylov/foursquare) and [accounts-foursquare](https://atmospherejs.com/msamoylov/accounts-foursquare)) will probably work better and I would be happy to lend a hand there if needed.

I have hidden the package from Atmosphere searches as you suggested.

**Comment by dandv** [comment]
Thanks Simon. In the meantime I found that @wehrlock's fork is the most actively maintained.
